<a href="https://colab.research.google.com/github/kgpark88/visionai/blob/main/day2/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor
https://www.programmersought.com/article/40345471852/

## CreateTensor

In [ ]:
import torch

Create a 5x3 uninitialized Tensor

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.9982e+03,  3.0901e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0901e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -1.0967e+03]])


Create a 5x3 randomly initializedTensor:

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4356, 0.9035, 0.5251],
        [0.7648, 0.6115, 0.8882],
        [0.4277, 0.8772, 0.9042],
        [0.0222, 0.1505, 0.1248],
        [0.5621, 0.6175, 0.3954]])


Create a 5x3 long type with all 0s Tensor

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Create directly based on data

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


You can also use existingTensor To create,   
this method will reuse the input by default Tensor Some attributes,   
such as data type, unless custom data type.

In [ ]:
x = x.new_ones(5, 3, dtype=torch.float64)  # The returned tensor has the same torch.dtype and torch.device by default
print(x)

x = torch.randn_like(x, dtype=torch.float) # Specify new data type
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5829, -1.0166, -1.4442],
        [ 0.1566,  0.7404,  1.6161],
        [ 0.8448, -0.7789,  0.0911],
        [-1.9529, -1.4881, -0.9876],
        [-0.9141, -0.4131,  0.3340]])


We can pass shape or size() To get Tensor shape:

In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


## Operation

### Arithmetic operation
In PyTorch, the same operation may have many forms. The following uses addition as an example.



Arithmetic operation

In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.4359, -0.7152, -0.5001],
        [ 0.8096,  1.5470,  1.9865],
        [ 1.4128, -0.2950,  0.1463],
        [-1.1597, -1.3962, -0.9642],
        [-0.6562,  0.1920,  0.5717]])


Additive form two

In [ ]:
print(torch.add(x, y))

tensor([[-0.4359, -0.7152, -0.5001],
        [ 0.8096,  1.5470,  1.9865],
        [ 1.4128, -0.2950,  0.1463],
        [-1.1597, -1.3962, -0.9642],
        [-0.6562,  0.1920,  0.5717]])


You can also specify the output:

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4359, -0.7152, -0.5001],
        [ 0.8096,  1.5470,  1.9865],
        [ 1.4128, -0.2950,  0.1463],
        [-1.1597, -1.3962, -0.9642],
        [-0.6562,  0.1920,  0.5717]])


Additive form three, inplace  
Note: PyTorch operation inplace version has a suffix _, E.g x.copy_(y), x.t_()

In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.4359, -0.7152, -0.5001],
        [ 0.8096,  1.5470,  1.9865],
        [ 1.4128, -0.2950,  0.1463],
        [-1.1597, -1.3962, -0.9642],
        [-0.6562,  0.1920,  0.5717]])


### index
- We can also use NumPy-like index operations to accessTensor
- The part that needs attention is:   
  The indexed result shares memory with the original data,   
  that is, if one is modified, the other will be modified accordingly.

In [ ]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # The source tensor has also been changed

tensor([ 0.4171, -0.0166, -0.4442])
tensor([ 0.4171, -0.0166, -0.4442])


### Change shape
Use view() to changeTensorshape:

In [ ]:
y = x.view(15)
z = x.view(-1, 5)  # -1 The dimension referred to can be derived from the values ​​of other dimensions
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


note view() Returned new Tensor With source Tensor   
Although there may be different size, But shared data Yes,   
that is, if you change one of them, the other will change accordingly.   
(As the name suggests, view only changes the viewing angle of this tensor,   
the internal data has not changed)

In [ ]:
x += 1
print(x)
print(y) # Also added 1

tensor([[ 1.4171,  0.9834,  0.5558],
        [ 1.1566,  1.7404,  2.6161],
        [ 1.8448,  0.2211,  1.0911],
        [-0.9529, -0.4881,  0.0124],
        [ 0.0859,  0.5869,  1.3340]])
tensor([ 1.4171,  0.9834,  0.5558,  1.1566,  1.7404,  2.6161,  1.8448,  0.2211,
         1.0911, -0.9529, -0.4881,  0.0124,  0.0859,  0.5869,  1.3340])


So what if we want to return a truly new copy (ie without sharing data memory)?  
Pytorch also provides are shape()   
You can change the shape, but this function does not guarantee that it will return a copy, so it is not recommended.   
Recommended first clone Create a copy and use it again view

In [ ]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.4171, -0.0166, -0.4442],
        [ 0.1566,  0.7404,  1.6161],
        [ 0.8448, -0.7789,  0.0911],
        [-1.9529, -1.4881, -0.9876],
        [-0.9141, -0.4131,  0.3340]])
tensor([ 1.4171,  0.9834,  0.5558,  1.1566,  1.7404,  2.6161,  1.8448,  0.2211,
         1.0911, -0.9529, -0.4881,  0.0124,  0.0859,  0.5869,  1.3340])


Another commonly used function is item(),   
It can convert a scalar Tensor Converted into a Python number:

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7192])
-0.7192049026489258


### Broadcast mechanism
Earlier we saw how to treat two identical shapes Tensor Do element wise operations.   
When two different shapes Tensor When calculating by element,   
the broadcasting mechanism may be triggered:   
first copy the elements appropriately to make these two Tensor Operate by element after the same shape.

In [ ]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### Operational memory overhead
As mentioned earlier, index operations will not open up new memory,  
but like y = x + y   
This kind of calculation will newly open the memory, and then y Point to new memory.   
To demonstrate this, we can use Python's own id Function:   
If the IDs of the two instances are the same, 
then their corresponding memory addresses are the same;   
otherwise, they are different.

In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 

False


If you want to assign the result to the original y  
We can use the index introduced earlier to replace the memory.   
In the following example, we put x + y The result passed [:] Write in y 
The corresponding memory.

In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

True


We can also use the operator full name function in out Parameter or addition operator += (That is add_())   
To achieve the above effects, for example torch.add(x, y, out=y) with y += x (y.add_(x))

In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True


### Tensor on GPU

How to use to() can Tensor Move between CPU and GPU (requires hardware support).

In [ ]:
# The following code will only be executed on the PyTorch GPU version
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # Create a Tensor on the GPU directly
    x = x.to(device)                       # Equivalent to .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()You can also change the data type at the same time

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
